### ISSUE TITLE
Better source-map

### ISSUE THREAD

**Issue by bpetetot** [bpetetot/pongmmo#14]
Currently, we have a source map that provides the transpiled sources :
`devtool: dev ? 'eval' : ''` 

It will be better to have the original sources :
`devtool: dev ? 'eval-source-map' : ''` 

But there is impact on build and re-build performances
See [here](http://webpack.github.io/docs/configuration.html#devtool) to have different source mapping options.

**Comment by fabienjuif** [comment]
I don't know how, but webpack handle this verywell with chrome (or vice versa).
Look at your source code, you will see the nice looking sources.
(this is the case in my codelab at least with same `devtool` option)

**Comment by fabienjuif** [comment]
I was wrong, eval produce a webpack (+transpilation) version of files.

**Comment by fabienjuif** [comment]
Fixed in #22
