### ISSUE TITLE
Project cleaning and organization

### ISSUE THREAD

**Issue by bpetetot** [bpetetot/pongmmo#16]
**Some project cleaning and organization ideas :** 
- Remove `docs` folder
- put `.babelrc` configuration in `package.json` ? minimize number of config files...
- organize multiple webpack configs
- propose code organization in `src` (for server, client, common...)
- move `assets` in `src` ?

**Comment by fabienjuif** [comment]
The way I see the project, we shouldn't organize source code in architecture layer (server/client/common) but in functionnal layer (player/ball/etc).

Because I would like to have like 80% of the code base shared between server and client, at least try to.

**Comment by fabienjuif** [comment]
Waiting for #6 to be completed

**Comment by fabienjuif** [comment]
#6 completed

**Comment by fabienjuif** [comment]
First attempt in #18
