### ISSUE TITLE
Events bus

### ISSUE THREAD

**Issue by fabienjuif** [bpetetot/pongmmo#34]
- [ ] The user should have responsives events
 - [ ] The events should be handle in one point in the application

**Comment by bpetetot** [comment]
p2.js already contains an Events bus named `EventEmitter`
Maybe, we can use it : 
http://schteppe.github.io/p2.js/docs/files/src_events_EventEmitter.js.html

Otherwise, there is EventEmitter from node.js : 
https://nodejs.org/api/events.html#events_events

**Comment by fabienjuif** [comment]
Every events (socketIO, PIXI events) should pass through this uniq Events bus.

**Comment by fabienjuif** [comment]
https://github.com/pazguille/jvent/blob/master/index.js

Change this to be async : https://github.com/pazguille/jvent/blob/master/index.js#L148

**Comment by fabienjuif** [comment]
Inherit from one of the eventEmitter and add an `onAsync` function.
Override `emit` method to calls alls `onAsync` before synchronous one.
